### ISSUE TITLE
Example broken

### ISSUE THREAD

**Issue by john-francis96** [Esri/wind-js#22]
dojo.io.script error
Error: Token Required.

/3.8compact/ (line 1057)

**Comment by jgravois** [comment]
duplicate of #19

i *still* recommend we make `gh-pages` the default branch of this repository and get rid of `master`. if i had the keys, i'd do it myself.

**Comment by john-francis96** [comment]
Using the gh-pages branch and everything works now. Thanks!

**Comment by jgravois** [comment]
i've gotten the two branches in sync (manually).  sorry for the confusion.
