### ISSUE TITLE
Special characters like λ and Δ becomes mojibake Î» and Î”

### ISSUE THREAD

**Issue by gloomcheng** [Esri/wind-js#29]
I've tried to clone code on my server but some of the code becomes mojibake like λ to Î», and I've tried to search related issue but I really have no idea what is the "right" keyword to search. Does anyone could help to solve this issue?

You may access the site on http://vps2.zhelang.com.tw/windy/wind-js/ and you will found error message "Uncaught SyntaxError: Invalid or unexpected token" on windy.js:27

I've tried to deploy it on my laptop (localhost) and remote server (vps2.zhelang.com.tw) all face same issue.

**Comment by jgravois** [comment]
i'm not able to access the link you shared. it is password protected.

what web server are you using? i don't have much experience in this area but i suspect you'll need to specify explicit UTF-8 encoding for the `.js` and `.html` or something like that.

**Comment by gloomcheng** [comment]
@jgravois You're right, it works after specify explicit UTF-8 encoding. Really appreciate it.

**Comment by jgravois** [comment]
excellent!
