### ISSUE TITLE
How can we use Dojo Toolkit offline instead of online dependency 

### ISSUE THREAD

**Issue by thatcuriousgirl** [Esri/wind-js#35]
I have been trying to use this application without internet connectivity but unable to do the same. I am not getting any altenative for Dojo Toolkit for offline applications. Can you please help me regarding the same.

**Comment by jgravois** [comment]
to host the application without an internet connection you'd need to install the entire ArcGIS API for JavaScript behind your firewall.

https://developers.arcgis.com/downloads/apis-and-sdks?product=javascript

**Comment by thatcuriousgirl** [comment]
![Partcile_Flow_Error](https://user-images.githubusercontent.com/48082322/54425318-0724b700-473b-11e9-858b-690e42cd2714.png)





I tried doing as per what you have said but I am getting this error

**Comment by thatcuriousgirl** [comment]
![Partcile_Flow_Error](https://user-images.githubusercontent.com/48082322/54425759-25d77d80-473c-11e9-9316-1e70fb7fe06d.png)





I have done as per the suggestion but still I am getting this error.

**Comment by thatcuriousgirl** [comment]
![Partcile_Flow_Error](https://user-images.githubusercontent.com/48082322/54426153-26244880-473d-11e9-8f5c-9580ec2f8d66.png)




I have done as per the suggestion but still getting this error.
